name: CI
on: [push, pull_request]
jobs:

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: yarn
      - name: Bootstrap Lerna
        run: yarn lerna bootstrap
      - name: Run build
        run: yarn build
      - name: Run test
        run: yarn test
